- hosts: ECHALOASUERTE
  remote_user: root
  roles:
  - { role: users, become: yes }
  - { role: nginx, become: yes }
  - { role: monitoring, become: yes  }
  - { role: echaloasuerte, datadir: "/data", become: yes  }
