- name: restart nginx
  service:
    name: nginx
    state: restarted
    sleep: 5
  become: yes

- name: restart all uwsgi
  service:
    name: uwsgi{{ item }}
    state: restarted
  become: yes
  with_sequence: count={{ uwsgi_n }}
  loop_control:
    pause: 3
  when: TRAVIS_DEPLOYMENT is not defined
