---
- set_fact:
    monit_version: "5.20.0"
    filebeat_version: "8.x"

- name: Fetch monit binary
  unarchive:
    src: "https://mmonit.com/monit/dist/binary/{{ monit_version }}/monit-{{ monit_version }}-linux-x64.tar.gz"
    dest: /tmp/
    remote_src: yes
    creates: /tmp/monit-{{ monit_version }}/bin/monit

- name: Copy monit binary to /usr/bin
  copy:
    src: /tmp/monit-{{ monit_version }}/bin/monit
    remote_src: yes
    dest: /usr/bin/monit
    owner: root
    group: root
    mode: 0755

- name: Install monit Upstart conf file
  copy:
    src: monit-upstart.conf
    dest: /etc/init/monit.conf
  when: ansible_service_mgr is undefined or ansible_service_mgr != "systemd"
  notify:
  - restart monit

- name: Install monit Systemd service file
  copy:
    src: monit-systemd.service
    dest: /etc/systemd/system/monit.service
    mode: 0644
  when: ansible_service_mgr is defined and ansible_service_mgr == "systemd"
  notify:
  - restart monit

- name: Create custom monitrc folders
  file:
    path: "/etc/monit/{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
  - monitrc.d
  - scripts

- name: Set monit master config file
  template:
    src: monitrc
    dest: "/etc/monit/monitrc"
    mode: 0700

- name: Install balance check scripts
  template:
    src: "{{ item }}"
    dest: "/etc/monit/scripts/{{ item }}"
    mode: 0700
  with_items:
  - check-lamadava-balance.sh
  - check-lamatok-balance.sh

- name: Copy monit configuration for services
  copy:
    src: "{{ item }}"
    dest: "/etc/monit/monitrc.d/{{ item }}"
    mode: 0700
  with_items:
  - fail2ban
  - nginx
  - system
  - docker
  - postgresql
  - lamadava
  - lamatok

- name: Delete old monit configuration files
  file:
    path: "/etc/monit/monitrc.d/{{ item }}"
    state: absent
  with_items:
  - mongodb

- name: Template uwsgi monit configuration file
  template:
    src: uwsgi
    dest: "/etc/monit/monitrc.d/uwsgi{{ item }}"
    mode: 0700
  with_sequence: count={{ uwsgi_n }}

- name: reload monit config
  shell: monit reload -c /etc/monit/monitrc

- name: Ensure monit is started and enabled on boot (systemd)
  service:
    name: monit
    state: started
    enabled: yes


# ELK, basic install from https://github.com/geerlingguy/ansible-role-filebeat/
- name: Ensure dependency is installed (Ubuntu).
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: present

- name: Add Filebeat repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ filebeat_version }}/apt stable main'
    state: present
    update_cache: true

- name: Install Filebeat and metricbeat
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - filebeat
  - metricbeat

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
  - filebeat
  - metricbeat

- name: Get logzio certificate
  get_url:
    url: https://raw.githubusercontent.com/logzio/public-certificates/master/AAACertificateServices.crt
    dest: /etc/filebeat/COMODORSADomainValidationSecureServerCA.crt
    mode: 0664
  notify:
  - restart filebeat
  - restart metricbeat

- name: Set filebeat config file
  template:
    src: filebeat.yml
    dest: "/etc/filebeat/filebeat.yml"
  notify:
  - restart filebeat

- name: Set metricbeat config file
  template:
    src: metricbeat.yml
    dest: "/etc/metricbeat/metricbeat.yml"
  notify:
  - restart metricbeat
