---
- name: Install packages needed from apt
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
  with_items:
  - libapache2-mod-php5
  - mariadb-server
  - python-mysqldb
  - php5-mysql

- name: Create a database user (for the first run only)
  mysql_user:
    name: "{{ mysqldb_admin_user }}"
    password: "{{ mysqldb_admin_password }}"
    priv: "*.*:ALL"
    host: localhost
    state: present
  ignore_errors: yes

- name: restart mysql
  service:
    name: mysql
    state: started
