---
- name: Install packages needed from apt
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
  become: yes
  with_items:
  - git
  - python-dev
  - libssl-dev
  - libffi-dev
  - python-pip
  - python3-pip
  - gettext
  - curl
  - fail2ban


- name: Install virtualenv from pip
  pip:
    executable: pip
    name: virtualenv
  become: yes

- name: Install virtualenv from pip3
  pip:
    executable: pip3
    name: virtualenv
  become: yes
