---
- name: Install packages needed from apt
  apt:
    pkg:
    - python2-minimal
    - git
    - python-dev
    - python3-dev
    - libssl-dev
    - libffi-dev
    - python3-pip
    - gettext
    - curl
    - fail2ban
    - jq
    state: present
    update-cache: yes
  become: yes

- name: Download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /opt/get-pip.py
  become: yes

- name: Install pip2
  command: python2 /tmp/get-pip.py
  args:
    creates: /usr/local/bin/pip2
  become: yes

- name: Install virtualenv from pip
  pip:
    executable: pip
    name: virtualenv
  become: yes

- name: Install virtualenv from pip3
  pip:
    executable: pip3
    name: virtualenv
  become: yes

- name: Install fail2ban action for echaluasuerte CF
  template:
    src: cloudflare-account.conf.action.j2
    dest: /etc/fail2ban/action.d/cloudflare-account.conf
    mode: 0640
  become: yes
  notify:
  - restart fail2ban


- name: Install fail2ban filter echaloasuerte-nginx
  copy:
    src: echaloasuerte-nginx.conf.filter
    dest: /etc/fail2ban/filter.d/echaloasuerte-nginx.conf
    mode: 0644
  become: yes
  notify:
  - restart fail2ban

- name: Install fail2ban jail for echaloasuerte
  copy:
    src: echaloasuerte.conf.jail
    dest: /etc/fail2ban/jail.d/echaloasuerte.conf
    mode: 0644
  become: yes
  notify:
  - restart fail2ban
