name: Manually triggered workflow for deployment
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Ansible playbook tags'
        required: true
  push:
    branches:
      - master
jobs:
  generate-vars:
    runs-on: ubuntu-latest
    outputs:
      ansible_hosts: '${{steps.set_vars.outputs.hosts_file}}'
      ansible_tags: '${{steps.set_vars.outputs.tags}}'
    steps:
      - name: Set vars
        id: set_vars
        run: |
          if [[ "${{github.ref}}" == "refs/heads/prod" ]]; then
              echo "::set-output name=hosts_file::environments/prod/hosts"
          elif [[ "${{github.ref}}" == "refs/heads/master" ]]; then
              echo "::set-output name=hosts_file::environments/dev/hosts"
          else
              echo "BRANCH NOT SUPPORTED: ${{github.ref}}"
              exit 1
          fi
          if [[ "${{github.event_name}}" == "push" ]]; then
              echo "::set-output name=tags::all"
          else
              echo "::set-output name=tags::${{ github.event.inputs.tags }}"
          fi


  deploy:
    runs-on: ubuntu-latest
    needs:
      - generate-vars
    steps:
      - name: Show deployment branch and tags
        run: |
          echo "Deploying from branch: ${{github.ref}}"
          echo "Deployment for tags: ${{ needs.generate-vars.outputs.ansible_tags }}"

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Turnstyle
        uses: softprops/turnstyle@8db075d65b19bf94e6e8687b504db69938dc3c65
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.2 requests

      - name: set ansible config secrets
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > .ansible-vault-password

      - name: Load ssh key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.AUTOMATION_SSH_KEY }}

      - name: run playbook
        run: |
          ansible-playbook -i ${{ needs.generate-vars.outputs.ansible_hosts }} config-eas3.yml \
            --vault-password-file .ansible-vault-password \
            --tags "${{ needs.generate-vars.outputs.ansible_tags }}" \
            --extra-vars "ansible_user=automation"
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
